### ISSUE TITLE
Task 0 checklist

### ISSUE THREAD

**Issue by killu21** [killu21/PT_tasks_MG#1]
# Repository check list

- [x] the task provides required feedback and has been submitted (needs grading)
- [x] the ability to clone the repository to the teacher's computer
- [x] README.md contains required information
- [x] build succeeded
- [x] all UT's are green

**Comment by mpostol** [comment]
Close any issue if it is done.
